server:
  port: 7004
spring:
  application:
    name: ZUUL-SERVER
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
zuul:
  routes:
    provider.serviceId: TEST-PROVIDER
    provider.path: /test/**
  ignored-services: "*"
  prefix: /server